source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

target 'CKLNetwork_Example' do
  pod 'Alamofire', '~> 5.2.1'
  pod 'CKLNetwork', :path => '../'
  
  target 'CKLNetwork_Tests' do
    inherit! :search_paths
  end
end
